### ISSUE TITLE
Please add licence

### ISSUE THREAD

**Issue by nikty** [k0ste/ansible-role-frr#4]
Hi!

I would like to use your code, but the licensing terms are not clear in this repo.

Could you please add License?

**Comment by k0ste** [comment]
Hi!

Actually this repo is public domain. If you know where I can download the LICENSE file for this - please share the link
Otherwise, you can put file via PR

Thanks!

**Comment by nikty** [comment]
FSF recommends CC0 for public domain works, so I think text from https://creativecommons.org/publicdomain/zero/1.0/legalcode.txt would suffice.

https://www.gnu.org/licenses/license-list.html#PublicDomain
https://www.gnu.org/licenses/license-list.html#CC0

**Comment by k0ste** [comment]
Thanks, file was added
